services:
  mysql:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./data:/app/data
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  mysql-data:
