services:
  mysql:
    image: mysql:5.7
    ports:
        - "32000:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
        - mysql
