"""Added Imports From Rotten

Revision ID: 01c3437ad245
Revises: 
Create Date: 2024-05-26 15:59:12.807473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c3437ad245'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name_basics',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('nconst', sa.String(length=255), nullable=False),
    sa.Column('primary_name', sa.String(length=255), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('death_year', sa.Integer(), nullable=True),
    sa.Column('primary_profession', sa.String(length=255), nullable=True),
    sa.Column('known_for_titles', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('netflix',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('show_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('director', sa.String(length=255), nullable=True),
    sa.Column('cast', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('date_added', sa.String(length=255), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('rating', sa.String(length=10), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('listed_in', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rotten_tomatoes_movies',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('rotten_tomatoes_link', sa.String(length=255), nullable=False),
    sa.Column('movie_title', sa.String(length=255), nullable=True),
    sa.Column('movie_info', sa.Text(), nullable=True),
    sa.Column('critics_consensus', sa.Text(), nullable=True),
    sa.Column('content_rating', sa.String(length=50), nullable=True),
    sa.Column('genres', sa.String(length=255), nullable=True),
    sa.Column('directors', sa.String(length=255), nullable=True),
    sa.Column('authors', sa.String(length=255), nullable=True),
    sa.Column('actors', sa.Text(), nullable=True),
    sa.Column('original_release_date', sa.Date(), nullable=True),
    sa.Column('streaming_release_date', sa.Date(), nullable=True),
    sa.Column('runtime', sa.String(length=50), nullable=True),
    sa.Column('production_company', sa.String(length=255), nullable=True),
    sa.Column('tomatometer_status', sa.String(length=50), nullable=True),
    sa.Column('tomatometer_rating', sa.Integer(), nullable=True),
    sa.Column('tomatometer_count', sa.Integer(), nullable=True),
    sa.Column('audience_status', sa.String(length=50), nullable=True),
    sa.Column('audience_rating', sa.Integer(), nullable=True),
    sa.Column('audience_count', sa.Integer(), nullable=True),
    sa.Column('tomatometer_top_critics_count', sa.Integer(), nullable=True),
    sa.Column('tomatometer_fresh_critics_count', sa.Integer(), nullable=True),
    sa.Column('tomatometer_rotten_critics_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('title_akas',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title_id', sa.String(length=255), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('types', sa.String(length=50), nullable=True),
    sa.Column('attributes', sa.String(length=50), nullable=True),
    sa.Column('is_original_title', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('title_basics',
    sa.Column('tconst', sa.String(length=255), nullable=False),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('is_adult', sa.Boolean(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tconst')
    )
    op.create_table('title_crew',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('tconst', sa.String(length=255), nullable=False),
    sa.Column('directors', sa.String(length=255), nullable=True),
    sa.Column('writers', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('title_principals',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('tconst', sa.String(length=255), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('nconst', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('job', sa.String(length=50), nullable=True),
    sa.Column('characters', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('title_ratings',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('tconst', sa.String(length=255), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('num_votes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('token_blocklist')
    op.drop_table('title_ratings')
    op.drop_table('title_principals')
    op.drop_table('title_crew')
    op.drop_table('title_basics')
    op.drop_table('title_akas')
    op.drop_table('rotten_tomatoes_movies')
    op.drop_table('netflix')
    op.drop_table('name_basics')
    # ### end Alembic commands ###
