"""Initial migration

Revision ID: a9f1fe3dd646
Revises: 
Create Date: 2024-06-02 18:34:32.812696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f1fe3dd646'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name_basics',
    sa.Column('nconst', sa.String(length=255), nullable=False),
    sa.Column('primary_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('nconst')
    )
    op.create_table('rotten_tomatoes_movies',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('rotten_tomatoes_link', sa.String(length=255), nullable=False),
    sa.Column('movie_title', sa.String(length=255), nullable=True),
    sa.Column('movie_info', sa.Text(), nullable=True),
    sa.Column('critics_consensus', sa.Text(), nullable=True),
    sa.Column('content_rating', sa.String(length=50), nullable=True),
    sa.Column('genres', sa.String(length=255), nullable=True),
    sa.Column('directors', sa.String(length=255), nullable=True),
    sa.Column('authors', sa.String(length=255), nullable=True),
    sa.Column('actors', sa.Text(), nullable=True),
    sa.Column('original_release_date', sa.Date(), nullable=True),
    sa.Column('streaming_release_date', sa.Date(), nullable=True),
    sa.Column('runtime', sa.String(length=50), nullable=True),
    sa.Column('production_company', sa.String(length=255), nullable=True),
    sa.Column('tomatometer_status', sa.String(length=50), nullable=True),
    sa.Column('tomatometer_rating', sa.Integer(), nullable=True),
    sa.Column('tomatometer_count', sa.Integer(), nullable=True),
    sa.Column('audience_status', sa.String(length=50), nullable=True),
    sa.Column('audience_rating', sa.Integer(), nullable=True),
    sa.Column('audience_count', sa.Integer(), nullable=True),
    sa.Column('tomatometer_top_critics_count', sa.Integer(), nullable=True),
    sa.Column('tomatometer_fresh_critics_count', sa.Integer(), nullable=True),
    sa.Column('tomatometer_rotten_critics_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('title_basics',
    sa.Column('tconst', sa.String(length=255), nullable=False),
    sa.Column('titleType', sa.String(length=100), nullable=True),
    sa.Column('originalTitle', sa.Text(), nullable=True),
    sa.Column('primaryTitle', sa.Text(), nullable=True),
    sa.Column('is_adult', sa.Boolean(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tconst')
    )
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('title_crew',
    sa.Column('tconst', sa.String(length=255), nullable=False),
    sa.Column('directors', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tconst'], ['title_basics.tconst'], ),
    sa.PrimaryKeyConstraint('tconst')
    )
    op.create_table('title_director',
    sa.Column('tconst', sa.String(length=255), nullable=False),
    sa.Column('nconst', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['nconst'], ['name_basics.nconst'], ),
    sa.ForeignKeyConstraint(['tconst'], ['title_basics.tconst'], ),
    sa.PrimaryKeyConstraint('tconst', 'nconst')
    )
    op.create_table('title_ratings',
    sa.Column('tconst', sa.String(length=255), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('num_votes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tconst'], ['title_basics.tconst'], ),
    sa.PrimaryKeyConstraint('tconst')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('title_ratings')
    op.drop_table('title_director')
    op.drop_table('title_crew')
    op.drop_table('users')
    op.drop_table('token_blocklist')
    op.drop_table('title_basics')
    op.drop_table('rotten_tomatoes_movies')
    op.drop_table('name_basics')
    # ### end Alembic commands ###
